package main

type Icommand interface {
	Execute(...interface{}) (interface{}, error)
}

type IGetter interface {
	Getter(interface{})
}

//Result Structure

type Detail struct {
	URL      string `json:"URL"`
	Title    string `json:"Title"`
	Describe string `json:"Describe"`
	Info     Info   `json:"Info"`
}

type Info struct {
	Publisher string `json:"Publisher"`
	Created   string `json:"Created"`
	Updated   string `json:"Updated"`
}

//Json Unmarshal Structure(Autogenerated Customized)

type AutoGenerated struct {
	Context    string `json:"@context"`
	Type       string `json:"@type"`
	ID         string `json:"@id"`
	Identifier string `json:"identifier"`
	Name       string `json:"name"`
	Creator    []struct {
		Name        string `json:"name"`
		Affiliation string `json:"affiliation"`
		ID          string `json:"@id,omitempty"`
		Identifier  string `json:"identifier,omitempty"`
	} `json:"creator"`
	Author []struct {
		Name        string `json:"name"`
		Affiliation string `json:"affiliation"`
		ID          string `json:"@id,omitempty"`
		Identifier  string `json:"identifier,omitempty"`
	} `json:"author"`
	DatePublished string   `json:"datePublished"`
	DateModified  string   `json:"dateModified"`
	Version       string   `json:"version"`
	Description   []string `json:"description"`
	Keywords      []string `json:"keywords"`
	License       struct {
		Type string `json:"@type"`
		Text string `json:"text"`
		URL  string `json:"url"`
	} `json:"license"`
	IncludedInDataCatalog struct {
		Type string `json:"@type"`
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"includedInDataCatalog"`
	Publisher struct {
		Type string `json:"@type"`
		Name string `json:"name"`
	} `json:"publisher"`
	Provider struct {
		Type string `json:"@type"`
		Name string `json:"name"`
	} `json:"provider"`
	SpatialCoverage []string `json:"spatialCoverage"`
	Distribution    []struct {
		Type        string `json:"@type"`
		Name        string `json:"name"`
		FileFormat  string `json:"fileFormat"`
		ContentSize int    `json:"contentSize"`
		Description string `json:"description"`
		ContentURL  string `json:"contentUrl"`
	} `json:"distribution"`
}
