package main

type Icommand interface {
	Execute(...interface{}) (interface{}, error)
}

type IGetter interface {
	Getter(interface{})
}

//Result Structure

type Detail struct {
	URL      string `json:"URL"`
	Title    string `json:"Title"`
	Describe string `json:"Describe"`
	Info     Info   `json:"Info"`
}

type Info struct {
	Publisher  string `json:"Publisher"`
	Created    string `json:"Created"`
	Updated    string `json:"Updated"`
	Identifier string `json:Identifier`
}

//Json Unmarshal Structure(Autogenerated Customized)

type AutoGenerated struct {
	Context             string        `json:"@context"`
	Type                string        `json:"@type"`
	ID                  string        `json:"@id"`
	Name                string        `json:"name"`
	Description         []string      `json:"description"`
	URL                 string        `json:"url"`
	Identifier          string        `json:"identifier"`
	Version             int           `json:"version"`
	IsAccessibleForFree bool          `json:"isAccessibleForFree"`
	Keywords            []interface{} `json:"keywords"`
	Creator             []struct {
		Type        string `json:"@type"`
		Name        string `json:"name"`
		GivenName   string `json:"givenName"`
		FamilyName  string `json:"familyName"`
		SameAs      string `json:"sameAs,omitempty"`
		Affiliation struct {
			Type   string `json:"@type"`
			SameAs string `json:"sameAs"`
			Name   string `json:"name"`
		} `json:"affiliation"`
	} `json:"creator"`
	Distribution struct {
		Type           string `json:"@type"`
		EncodingFormat string `json:"encodingFormat"`
		ContentURL     string `json:"contentUrl"`
	} `json:"distribution"`
	TemporalCoverage string        `json:"temporalCoverage"`
	SpatialCoverage  []interface{} `json:"spatialCoverage"`
	Citation         string        `json:"citation"`
	License          struct {
		Type    string `json:"@type"`
		Name    string `json:"name"`
		License string `json:"license"`
	} `json:"license"`
	Publisher struct {
		ID        string `json:"@id"`
		Type      string `json:"@type"`
		LegalName string `json:"legalName"`
		Name      string `json:"name"`
		URL       string `json:"url"`
	} `json:"publisher"`
	Provider struct {
		ID string `json:"@id"`
	} `json:"provider"`
}
